### ISSUE TITLE
Unable to create a 1.22 Shoot

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-networking-calico#195]
**How to categorize this issue?**

/area networking
/kind bug

**What happened**:
After the https://github.com/gardener/gardener-extension-networking-calico/pull/193 the Network reconciliation for a K8s 1.22 Shoot fails with:
```
E0708 09:44:01.579736       1 runtime.go:78] Observed a panic: &errors.errorString{s:"could not find image \"calico-podtodaemon-flex\" opts runtime version 1.22.11 target version 1.22.11"} (could not find image "calico-podtodaemon-flex" opts runtime version 1.22.11 target version 1.22.11)
goroutine 301 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1a7db20?, 0xc000cbc400})
	/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x86
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:106 +0x6f
panic({0x1a7db20, 0xc000cbc400})
	/usr/local/go/src/runtime/panic.go:838 +0x207
k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
github.com/gardener/gardener-extension-networking-calico/pkg/imagevector.findImage({0x1d22a23, 0x17}, {0xc000ac6cf0, 0x7})
	/go/src/github.com/gardener/gardener-extension-networking-calico/pkg/imagevector/image_finders.go:25 +0x1df
github.com/gardener/gardener-extension-networking-calico/pkg/imagevector.CalicoFlexVolumeDriverImage(...)
	/go/src/github.com/gardener/gardener-extension-networking-calico/pkg/imagevector/image_finders.go:51
github.com/gardener/gardener-extension-networking-calico/pkg/charts.ComputeCalicoChartValues(0xc00056a1c0, 0xc000cbc060?, 0x1, {0xc000ac6cf0, 0x7}, 0x1, 0xd5?)
	/go/src/github.com/gardener/gardener-extension-networking-calico/pkg/charts/utils.go:164 +0x3b4
github.com/gardener/gardener-extension-networking-calico/pkg/charts.RenderCalicoChart({0x1fa8c80, 0xc000cbc070}, 0xc000d8d6e8?, 0x1?, 0x1?, {0xc000ac6cf0?, 0x0?}, 0x0?, 0x0?)
	/go/src/github.com/gardener/gardener-extension-networking-calico/pkg/charts/values.go:30 +0x45
github.com/gardener/gardener-extension-networking-calico/pkg/controller.(*actuator).Reconcile(0xc00009d860, {0x1fc24d0, 0xc0003335c0}, 0xc00056a1c0, 0xc000dc8ea0)
	/go/src/github.com/gardener/gardener-extension-networking-calico/pkg/controller/actuator_reconcile.go:131 +0x4a8
github.com/gardener/gardener/extensions/pkg/controller/network.(*reconciler).reconcile(0xc00027fec0, {0x1fc24d0, 0xc0003335c0}, 0xc000e57bf0?, 0x1fc74b0?, {0x1d0f4e4, 0x9})
	/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/github.com/gardener/gardener/extensions/pkg/controller/network/reconciler.go:139 +0x235
github.com/gardener/gardener/extensions/pkg/controller/network.(*reconciler).Reconcile(0xc00027fec0, {0x1fc2578, 0xc000e57bf0}, {{{0xc000b0c700?, 0x1fc2578?}, {0xc000904d16?, 0x1fce080?}}})
	/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/github.com/gardener/gardener/extensions/pkg/controller/network/reconciler.go:125 +0xea8
github.com/gardener/gardener/pkg/controllerutils/reconciler.(*operationAnnotationWrapper).Reconcile(0xc00077ede0, {0x1fc2578, 0xc000e57bf0}, {{{0xc000b0c700?, 0x1bfba00?}, {0xc000904d16?, 0x30?}}})
	/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/github.com/gardener/gardener/pkg/controllerutils/reconciler/operation_annotation_wrapper.go:73 +0x9b5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0005fc0b0, {0x1fc2578, 0xc000e57b30}, {{{0xc000b0c700?, 0x1bfba00?}, {0xc000904d16?, 0x4041f4?}}})
	/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114 +0x27e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005fc0b0, {0x1fc24d0, 0xc0007d8c80}, {0x1b179e0?, 0xc00005a720?})
	/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311 +0x349
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005fc0b0, {0x1fc24d0, 0xc0007d8c80})
	/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/src/github.com/gardener/gardener-extension-networking-calico/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:223 +0x31c
```

**What you expected to happen**:
No such error.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: fdd6f551602229c5219bbe614f1ddc571d634394
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
Fixed with https://github.com/gardener/gardener-extension-networking-calico/pull/194

/close
